### ISSUE TITLE
FreeBSD build: 3 small CMake fixes (config.h include path, Threads link, cmake_minimum)

### ISSUE THREAD

**Issue by kleinmatic** [gdwnldsKSC/es40#120]
Built `ES40-Emu/es40` on **FreeBSD 15.1** (clang/libc++, base libpcap, `pkg install sdl3`, cmake 3.31 from pkg) and it works great — boots OpenVMS Alpha 8.4 under the JIT, networks fine via libpcap, and is noticeably faster than the AXPbox fork. The C++ itself compiles 100% clean on clang/libc++; the only blockers were three small CMake config gaps. Sharing the fixes in case they're useful — happy to turn this into a PR.

Headless configure used:
```
cmake -DCMAKE_BUILD_TYPE=Release -DES40_DISABLE_IDB=ON -DES40_DISABLE_LSS_LSM=ON -DES40_DISABLE_ASMJIT=OFF ..
```

**1. `cmake_minimum_required(VERSION 4.1)`** — FreeBSD's pkg tops out at cmake 3.31. Lowering the floor to 3.31 builds with no other changes, so 4.1 may be higher than actually needed.

**2. Generated `config.h` isn't on the include path.** `configure_file(src/config.h.cmake src/config.h)` writes `build/src/config.h`, but the targets only include the *source* dirs, so `StdAfx.h`'s `#include "config.h"` fails:
```
src/StdAfx.h:157:10: fatal error: 'config.h' file not found
```
Fix: add `${CMAKE_CURRENT_BINARY_DIR}/src` to the include path.

**3. Threads aren't linked** (the `NOT WIN32` path). Final link fails with undefined `pthread_create` / `pthread_setschedparam` — FreeBSD keeps pthreads in `libthr` and needs `-pthread`. Fix: `find_package(Threads REQUIRED)` + link `Threads::Threads`.

Diff against current `main`:
```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 1543ad7..3ebdb2b 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -1,4 +1,4 @@
-cmake_minimum_required(VERSION 4.1)
+cmake_minimum_required(VERSION 3.31)
 
 project(ES40 LANGUAGES C CXX)
 
@@ -150,6 +150,7 @@ if (NOT WIN32)
     set(HAVE_SYS_TIME ${TM_IN_SYS_TIME})
 
     configure_file(src/config.h.cmake src/config.h)
+    include_directories(${CMAKE_CURRENT_BINARY_DIR}/src)
     add_compile_definitions(HAVE_CONFIG_H)
 endif()
 
@@ -290,6 +291,7 @@ if (NOT ES40_DISABLE_NETWORKING)
 endif()
 
 list(APPEND ES40_INCLUDES
+    ${CMAKE_CURRENT_BINARY_DIR}/src
     src/
     src/emu
     src/base
@@ -328,7 +330,9 @@ if (NOT ES40_DISABLE_LSS_LSM)
     endif()
 endif()
 
+find_package(Threads REQUIRED)
 target_link_libraries(es40 PUBLIC ${ES40_LIBRARIES})
+target_link_libraries(es40 PUBLIC Threads::Threads)
 if (NOT ES40_DISABLE_IDB)
     target_link_libraries(es40_idb PUBLIC ${ES40_LIBRARIES})
     if (NOT ES40_DISABLE_ASMJIT)
```

Thanks for the great emulator — and for the help on the DEC Discord getting it running on FreeBSD.

**Comment by meowthink** [comment]
Oh that's my fault.
On 2., I was use autotools thus there's a src/config.h in project root, your patch is correct.
On 3., I think your patch is not working well with lss lsm idb etc. see mine below.
btw 1. I think cmake 3.24(in par with asmjit) is ok.

```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 1543ad7..72ed100 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -1,4 +1,4 @@
-cmake_minimum_required(VERSION 4.1)
+cmake_minimum_required(VERSION 3.24)

 project(ES40 LANGUAGES C CXX)

@@ -150,6 +150,7 @@ if (NOT WIN32)
     set(HAVE_SYS_TIME ${TM_IN_SYS_TIME})

     configure_file(src/config.h.cmake src/config.h)
+    include_directories(${CMAKE_CURRENT_BINARY_DIR}/src)
     add_compile_definitions(HAVE_CONFIG_H)
 endif()

@@ -289,7 +290,14 @@ if (NOT ES40_DISABLE_NETWORKING)
     endif()
 endif()

+if (NOT WIN32)
+    set(THREADS_PREFER_PTHREAD_FLAG ON)
+    find_package(Threads REQUIRED)
+    list(APPEND ES40_LIBRARIES Threads::Threads)
+endif()
+
 list(APPEND ES40_INCLUDES
+    ${CMAKE_CURRENT_BINARY_DIR}/src
     src/
     src/emu
     src/base
```

**Comment by mvorl** [comment]
And while we're at it, we could fix the URL and version information
```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 1543ad7..25c9363 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -131,14 +131,14 @@ if (NOT WIN32)
     check_include_file("X11/X.h" HAVE_X11)
 
     set(PACKAGE \"${PROJECT_NAME}\")
-    set(PACKAGE_BUGREPORT "\"https://github.com/gdwnldsKSC/es40/issues/new\"")
+    set(PACKAGE_BUGREPORT "\"https://github.com/ES40-Emu/es40/issues/new\"")
     string(TOLOWER ${PROJECT_NAME} PACKAGE_NAME_L)
     set(PACKAGE_NAME \"${PACKAGE_NAME_L}\")
-    set(PROJECT_VERSION 0.65)
+    set(PROJECT_VERSION 0.74)
     set(PACKAGE_VERSION \"${PROJECT_VERSION}\")
     set(PACKAGE_STRING "\"${PACKAGE_NAME_L} ${PROJECT_VERSION}\"")
     set(PACKAGE_TARNAME \"${PACKAGE_NAME_L}.tar.gz\")
-    set(PACKAGE_URL "\"https://github.com/gdwnldsKSC/es40/issues\"")
+    set(PACKAGE_URL "\"https://github.com/ES40-Emu/es40/issues\"")
     set(VERSION \"${PROJECT_VERSION}\")
 
     set(RETSIGTYPE "void")
```

**Comment by gdwnldsKSC** [comment]
These have been merged in. Thanks!
